// default package
// Generated Jun 4, 2020 4:15:33 PM by Hibernate Tools 5.4.14.Final

/**
 * SvMonhoc generated by hbm2java
 */
package pojo;

@SuppressWarnings("serial")
public class SvMonhoc implements java.io.Serializable {

	private int stt;
	private int mssv;
	private String maLop;
	private String maMon;
	private Float gk;
	private Float ck;
	private Float diemKhac;
	private Float diemTong;

	public SvMonhoc() {
	}

	public SvMonhoc(int stt) {
		this.stt = stt;
	}

	public SvMonhoc(int stt, int mssv, String maLop, String maMon, Float gk, Float ck, Float diemKhac, Float diemTong) {
		this.stt = stt;
		this.mssv = mssv;
		this.setMaLop(maLop);
		this.maMon = maMon;
		this.gk = gk;
		this.ck = ck;
		this.diemKhac = diemKhac;
		this.diemTong = diemTong;
	}

	public int getStt() {
		return stt;
	}

	public void setStt(int stt) {
		this.stt = stt;
	}

	public int getMssv() {
		return mssv;
	}

	public void setMssv(int mssv) {
		this.mssv = mssv;
	}
	
	public String getMaLop() {
		return maLop;
	}

	public void setMaLop(String maLop) {
		this.maLop = maLop;
	}


	public String getMaMon() {
		return maMon;
	}

	public void setMaMon(String maMon) {
		this.maMon = maMon;
	}

	public Float getGk() {
		return this.gk;
	}

	public void setGk(Float gk) {
		this.gk = gk;
	}

	public Float getCk() {
		return this.ck;
	}

	public void setCk(Float ck) {
		this.ck = ck;
	}

	public Float getDiemKhac() {
		return this.diemKhac;
	}

	public void setDiemKhac(Float diemKhac) {
		this.diemKhac = diemKhac;
	}

	public Float getDiemTong() {
		return this.diemTong;
	}

	public void setDiemTong(Float diemTong) {
		this.diemTong = diemTong;
	}

	
}
