// default package
// Generated Jun 4, 2020 4:15:33 PM by Hibernate Tools 5.4.14.Final
package pojo;
import java.util.HashSet;
import java.util.Set;

/**
 * Tkb generated by hbm2java
 */

@SuppressWarnings("serial")
public class Tkb implements java.io.Serializable {

	private int stt;
	private Sinhvien sinhvien;
	private String maMon;
	private String tenMon;
	private String phongHoc;
	private Set svMonhocs = new HashSet(0);

	public Tkb() {
	}

	public Tkb(int stt) {
		this.stt = stt;
	}

	public Tkb(int stt, Sinhvien sinhvien, String maMon, String tenMon, String phongHoc, Set svMonhocs) {
		this.stt = stt;
		this.sinhvien = sinhvien;
		this.maMon = maMon;
		this.tenMon = tenMon;
		this.phongHoc = phongHoc;
		this.svMonhocs = svMonhocs;
	}

	public int getStt() {
		return this.stt;
	}

	public void setStt(int stt) {
		this.stt = stt;
	}

	public Sinhvien getSinhvien() {
		return this.sinhvien;
	}

	public void setSinhvien(Sinhvien sinhvien) {
		this.sinhvien = sinhvien;
	}

	public String getMaMon() {
		return this.maMon;
	}

	public void setMaMon(String maMon) {
		this.maMon = maMon;
	}

	public String getTenMon() {
		return this.tenMon;
	}

	public void setTenMon(String tenMon) {
		this.tenMon = tenMon;
	}

	public String getPhongHoc() {
		return this.phongHoc;
	}

	public void setPhongHoc(String phongHoc) {
		this.phongHoc = phongHoc;
	}

	public Set getSvMonhocs() {
		return this.svMonhocs;
	}

	public void setSvMonhocs(Set svMonhocs) {
		this.svMonhocs = svMonhocs;
	}

}
